name: PetCare
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  google_fonts: ^3.0.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  pdf: ^3.7.1
  font_awesome_flutter: ^10.1.0 # Añade esta línea para Font Awesome Flutter
  fl_chart: ^0.68.0
  flutter_typeahead: ^4.0.0
  uuid: ^4.4.2
  table_calendar: ^3.1.2
  geolocator: ^9.0.2
  mercadopago_sdk: ^1.3.0
  url_launcher: ^6.1.7
  uni_links: ^0.5.1
  flutter_local_notifications: ^14.1.5
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  printing: ^5.11.0
  flutter_facebook_auth: ^5.0.0
  local_auth: ^2.1.0
  video_player: ^2.9.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_custom_tabs: ^2.1.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_messaging: ^15.0.0
  firebase_core_platform_interface: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.1.5
  path_provider: ^2.1.4
  share_plus: ^7.2.2
  stomp_dart_client: ^2.0.0
  flutter_nfc_kit: ^3.4.2
  shared_preferences: ^2.2.3
  firebase_database: ^11.0.0
  firebase_performance: ^0.10.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  printing: ^5.10.4

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/logos/
    - lib/assets/iconos/